### ISSUE TITLE
compiled project installed on device, TikTok is working but the tweak is still not showing or working.

### ISSUE THREAD

**Issue by atebitsy** [tuxi/TikTok-Tweaks#5]
compiled project installed on device, TikTok is working but the tweak is still not showing or working.

iOS 15.1
iPHONE 13 PRO MAX, also tried on iPhone 12 PRO MAX and TikTok is working but the tweak is still not showing or working.

I don't understand what's going wrong? It doesn't seem like the code is being executed, would you know why that is happening?

**Comment by tuxi** [comment]
I think it may be caused by insert dylib failure. You can refer to this problem in [MonkeyDev](https://github.com/AloneMonkey/MonkeyDev/issues/270#issuecomment-900191360) to solve it.

**Comment by novitae** [comment]
Same on iPhone 6, I pushed the edited .ipa (I edited the info.plist) file on the jailbroken iPhone, then installed it with Filza. Shaking the phone as you told here https://github.com/tuxi/TikTok-Tweaks/issues/4 doesn't work.

**Comment by arslan2012** [comment]
在应用 https://github.com/AloneMonkey/MonkeyDev/issues/270#issuecomment-900191360 的修复之前，是看不了视频的，应用了这个修复之后可以不拔卡看视频了，所以应该是注入成功了，但是菜单还是摇不出来。。。。
