### ISSUE TITLE
altstore无法安装

### ISSUE THREAD

**Issue by imzhucn** [tuxi/TikTok-Tweaks#6]
TikTok-22.0.0.ipa
iphone 11
altstore
错误提示：
Device iPhone 12,1 not in Supported Devices list
for com.zhiliaoapp musically ZZ46F2CC5N:(
"iPhone7,1"
"iPhone8,2"
)

**Comment by arslan2012** [comment]
我怀疑是README里的ipa有问题

我用altstore安装，也报了这个错

用sideloady关闭版本检查强制安装，安装成功后的app无法登录无法打开设置界面。

克隆项目放入22.5.0的脱壳ipa并用xcode安装，一切正常可用。

**Comment by arslan2012** [comment]
@tuxi 突然反应过来，README里面的是不是没有编译的过的脱壳ipa啊？感觉大家都以为是编译好的ipa直接放到alt store里面了🤣🤣🤣🤣🤣

**Comment by tuxi** [comment]
这是因为info.plist中的UISupportedDevices限制了可以安装的设备，你删除这一项，重新运行项目吧。

**Comment by arslan2012** [comment]
嗯，已经安装成功了呢，贡献一下我的22.5.0的脱壳ipa 链接: https://pan.baidu.com/s/1YDbOg9a3qlJAHlHwCgsSCg?pwd=6cei 提取码: 6cei

**Comment by tuxi** [comment]
谢谢恭喜🍺

**Comment by imzhucn** [comment]
> dDevices限制了可以安装的设备，你删除这一项，重新运行项

我试试看，谢谢大佬
