### ISSUE TITLE
build的时候报了个错误

### ISSUE THREAD

**Issue by GL8666** [tuxi/TikTok-Tweaks#8]
![screenshot-20220421-143115](https://user-images.githubusercontent.com/2344801/164388774-5d555807-beec-4723-93e9-2da65c2a3a25.png)

**Comment by Apibug** [comment]
这是xcode版本高吧，我也经常遇到，clean下就行

**Comment by tuxi** [comment]
确保app包在目录下的话，clear 一下呢，然后再编译
